### ISSUE TITLE
Add removable-media plug

### ISSUE THREAD

**Issue by biinari** [errata-ai/vale-snap#1]
Allow users to connect with [`removable-media` interface](https://snapcraft.io/docs/removable-media-interface) for use with removable media. This would help with users that have projects on a USB drive or other filesystem.

It seems reasonable for this to not be auto-connected. Instructions would be useful in the README to connect:

```sh
snap connect vale:removable-media
```

## Justification

Due to size constraints on my primary SSD, I have some of my projects on another drive mounted at `/mnt/store`.

## Workaround

It is possible to bind-mount these other mounted filesystems under the home directory. That would not be convenient for removable media.

Example:

```sh
mkdir $HOME/store
mount --bind /mnt/store $HOME/store
```

**Comment by alexmurray** [comment]
Thanks for the suggestion and the detailed rationale - added in https://github.com/errata-ai/vale-snap/commit/6f4213e5d7111eb5e2ea4c2be2b93a939f36527d

**Comment by biinari** [comment]
Nice, thanks for putting this in so quickly.

**Comment by alexmurray** [comment]
FYI - the updated snap is now published in the stable channel.
